test_script:
- cd C:\Qt
- dir Qt5WebEngine.dll /s
- dir C:\Qt\5.6
- dir C:\Qt\5.6.3
- dir C:\Qt\5.9
- dir C:\Qt\5.9.7
- dir C:\Qt\5.10
- dir C:\Qt\5.10.1
- dir C:\Qt\5.11
- dir C:\Qt\5.11.3
- dir C:\Qt\5.12
- dir C:\Qt\5.12.1
- dir C:\Qt\Tools

- dir C:\Qt\5.11.2\msvc2015\bin

build: off
