init: 
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test_script:
- dir C:\Qt\6.2
- dir C:\Qt\tools
- dir C:\Qt\tools\QtInstallerFramework
- ps: .\test.ps1

build: off
