init: 
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  #- ps: Start-Service MySQL80
#services:
 # - mysql
before_test: 
  - cmd: |
      "C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql" -u root -p'Password12!' -e 'CREATE DATABASE temp_CI'
test_script:
  - cmd: |
      "C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql" -u root -p'Password12!' -e 'DROP DATABASE IF EXISTS temp_CI'
  - dir C:\Qt\6.2
  - dir C:\Qt\tools
  - dir C:\Qt\tools\QtInstallerFramework
  - ps: .\test.ps1

build: off
